#!/bin/bash

DIST_DIR="/home/melo/svn_cocoma/dist/deb_dist/cocoma-0.1/debian/"
SVN_DIR="/home/melo/svn_cocoma/cocoma/extra_tobe_fixed/deb-files/"


python setup.py sdist
cd dist/
#rsync -auz $DIST_DIR $SVN_DIR

py2dsc -m 'Carmelo Ragusa <carmelo.ragusa@sap.com>' cocoma-0.1.tar.gz 

cd deb_dist/cocoma-0.1/

#rsync -auz $SVN_DIR $DIST_DIR

cp /home/melo/svn_cocoma/cocoma/extra_tobe_fixed/deb-files/* /home/melo/svn_cocoma/dist/deb_dist/cocoma-0.1/debian/

debuild -us -uc
