#!/bin/sh

# Make sure python is 2.7 or later
PYTHON_OK=`python -c 'import sys; print (sys.version_info >= (2, 7) and "1" or "0")'`

#echo "python ok: $PYTHON_OK"

if [ "$PYTHON_OK" = '0' ]; then
	echo "Python version too old"
	echo "Downloading python 2.7.3 ..."
	curl -O http://www.python.org/ftp/python/2.7.3/Python-2.7.3.tgz
	tar xzvf Python-2.7.3.tgz
	cd Python-2.7.3
	./configure
	make
	make install
	cd ..
	echo "Cleaning Python installation files ..."
	rm -fr Python-2.7.3 Python-2.7.3.tgz
fi

if [ `pip --version | grep -c "python 2.7"` = 0 ]; then
	curl -O http://python-distribute.org/distribute_setup.py
	python distribute_setup.py
	echo "Downloading pip for python 2.7 ..."
	curl -O https://raw.github.com/pypa/pip/master/contrib/get-pip.py
	python get-pip.py
	echo "Cleaning pip installation files ..."
	rm distribute_setup.py get-pip.py
fi

echo "Modifing ccmsh permissions ..."
chmod +x /usr/share/pyshared/cocoma/bin/ccmsh.py

echo "Modifing scheduler permissions ..."
chmod +x /usr/share/pyshared/cocoma/bin/Scheduler.py

echo "Modifing ccmshAPI permissions ..."
chmod +x /usr/share/pyshared/cocoma/bin/ccmshAPI.py

echo "Installing python apscheduler, bottle, pyro4 and psutil ..."
pip  install --upgrade apscheduler pyro4 bottle psutil

echo "Checking COCOMA env variable ..."

if ! grep -q "export COCOMA=\"/usr/share/pyshared/cocoma\"" /etc/profile ; then
	echo "Adding COCOMA env variable ..."
	echo "export COCOMA=\"/usr/share/pyshared/cocoma\"" >> /etc/profile
fi

. /etc/profile

